language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '12'
  - '10'
  - '8'
after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
